INSERT INTO CONSOLE(CONSOLE_NAME) VALUES ('PS3');

INSERT INTO GAME(TITLE, PROGRESSION, CONSOLE_ID) VALUES ( 'uncharted drake s fortune', 2, (SELECT ID FROM CONSOLE WHERE CONSOLE_NAME= 'PS3'));
INSERT INTO GAME(TITLE, PROGRESSION, CONSOLE_ID) VALUES ( 'battlefield3 Limited edition', 2, (SELECT ID FROM CONSOLE WHERE CONSOLE_NAME= 'PS3'));
INSERT INTO GAME(TITLE, PROGRESSION, CONSOLE_ID) VALUES ( 'call of duty Modern warfare 2', 2, (SELECT ID FROM CONSOLE WHERE CONSOLE_NAME= 'PS3'));