--liquibase formatted sql

--changeset jgt:1
CREATE TABLE DATABASECHANGELOGLOCK(
    ID INTEGER NOT NULL,
    LOCKED BOOLEAN NOT NULL,
    LOCKGRANTED TIMESTAMP,
    LOCKEDBY VARCHAR(255),
    CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY(ID)
);

--changeset jgt:2
CREATE TABLE DATABASECHANGELOG(
  ID VARCHAR(63) NOT NULL,
  AUTHOR VARCHAR(63) NOT NULL,
  FILENAME VARCHAR(200) NOT NULL,
  DATEEXECUTED TIMESTAMP NOT NULL,
  MD5SUM VARCHAR(32),
  DESCRIPTION VARCHAR(255),
  COMMENTS VARCHAR(255),
  TAG VARCHAR(255),
  LIQUIBASE VARCHAR(10),
  CONSTRAINT PK_DATABASECHANGELOG PRIMARY KEY(ID,AUTHOR,FILENAME)
);

--changeset jgt:3
CREATE TABLE USER (
    ID bigint NOT NULL,
    EMAIL VARCHAR(255),
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    CONSTRAINT PK_USER PRIMARY KEY (id)
);
